services:
    cs_1.6:
        build: .
        container_name: CS_1.6
        ports:
            - "27015:27015/udp"
            - "27015:27015/tcp"
        volumes:
            - ./cstrike:/opt/hlds/cstrike:U
        restart: always
